services:

  # https://hub.docker.com/r/libretranslate/libretranslate
  # http://0.0.0.0:5050/
  translate:
    container_name: ${PROJECT_NAME}-translate
    image: libretranslate/libretranslate:latest
    restart: always
    expose:
      - "5050"
    ports:
      - "${PROJECT_IP}:5050:5000"